### ISSUE TITLE
Focused button styling - 'Sign up' or start browsing

### ISSUE THREAD

**Issue by wing5wong** [JeffreyWay/Laracasts-Bugs#66]
use tab to navigate through your links until you hit the sign up, or start browsing buttons.
they have a brownish background and dark gray text - doesn seem to match your hover states, and is hard to read.

i assume you would like it the same as your hover styles, in which case you just need to set the color and border

``` css
.btn-transparent:hover, .btn-transparent:focus {
border: 1px solid rgba(232,74,26,0.9);
color: #fff;
}
```
